[package]
name = "mult-persistence"
version = "0.1.0"
authors = ["Michael Winkworth"]
edition = "2018"

[dependencies]
rayon = "1.3.0"

[dev-dependencies]
criterion = "0.3.2"

[[bench]]
name = "calc_slice"
harness = false
